image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  REDIS_HOST: redis-master.default.svc.cluster.local
  ESHOST: elastic-cluster-es-http.svc.cluster.local
  MONGO: "mongodb://se3-cluster-1.se3-cluster-svc.mongodb.svc.cluster.local"
  KUBECONFIG: /etc/deploy/config
  MAVEN_OPTS: "-Dmaven.repo.local=/opt/cache/.m2/repository"

stages:
  - package
  - test
  - build
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: package
  script: 
    - mvn -B -DskipTests clean package
    - cp target/app.jar /opt/cache

maven-test:
  image: maven:3-jdk-8
  stage: test
  script: 
    - mkdir target
    - cp /opt/cache/app.jar target/app.jar 
    - mvn test
  artifacts:
    paths:
      - target/surefire-reports/*.xml

build-image:
  stage: build
  script:
    - ls target
    - cp /opt/cache/app.jar target/app.jar
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID .
    - docker push $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID

deploy-k8s:
  stage: deploy
  script:
    - sed -i "s/TAG/$CI_PIPELINE_ID/g" deployment.yaml
    - sed -i "s/EUSER/$ES_USER/g" deployment.yaml
    - sed -i "s/EPASS/$ES_PASS/g" deployment.yaml
    - cat deployment.yaml
    - kubectl apply -f deployment.yaml