image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  REDIS_HOST: redis-master.default.svc.cluster.local
  ESHOST: elastic-cluster-es-http.svc.cluster.local
  MONGO: "mongodb://se3-cluster-1.se3-cluster-svc.mongodb.svc.cluster.local"
  KUBECONFIG: /etc/deploy/config
  MAVEN_OPTS: "-Dmaven.repo.local=/opt/cache/.m2/repository"
  REGISTRY: "backend-oasis"

stages:
  - package
  - test
  - build

maven-build:
  image: maven:3-jdk-8
  stage: package
  script: "mvn -B -DskipTests clean package"

maven-test:
  image: maven:3-jdk-8
  stage: test
  script: "mvn test"
  artifacts:
    paths:
      - target/surefire-reports/*.xml

build-image:
  stage: build
  script:
    - docker login -u $HUB_USER -p $HUB_PASS
    - docker build -t $HUB_USER/$REGISTRY:$CI_COMMIT_SHORT_SHA .
    - docker push $HUB_PASS/$REGISTRY:latest