image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  REDIS_HOST: redis-master.default.svc.cluster.local
  ESHOST: elastic-cluster-es-http.svc.cluster.local
  MONGO: "mongodb://se3-cluster-1.se3-cluster-svc.mongodb.svc.cluster.local"
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
  - package
  - test

cache:
  paths:
    - .m2/repository/


maven-build:
  image: maven:3-jdk-8
  stage: package
  script: "mvn -B -DskipTests clean package"
  artifacts:
    paths:
      - target/*.jar

maven-test:
  image: maven:3-jdk-8
  stage: test
  script: "mvn test"
