apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-oasis
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-oasis
  template:
    metadata:
      labels:
        app: backend-oasis
    spec:
      strategy:
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1
        type: RollingUpdate
      containers:
      - name: backend-oasis
        image: greenw00d/backend-oasis:TAG
        imagePullPolicy: Always
        env:
          - name: REDIS_HOST
            value: redis-master.default.svc.cluster.local
          - name: ESHOST
            value: elastic-cluster-es-http.default.svc.cluster.local
          - name: MONGO
            value: mongodb://se3-cluster-1.se3-cluster-svc.mongodb.svc.cluster.local
          - name: ES_USER
            value: EUSER
          - name: ES_PASS
            value: EPASS
        readinessProbe:
            periodSeconds: 5
            httpGet:
              path: /actuator/health
              port: 8081
        livenessProbe:
            periodSeconds: 10
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 360
        resources:
          limits:
            memory: "1Gi"
            cpu: "0.5"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: backend-oasis-svc
  namespace: default
spec:
  ports:
  - port: 8081
    targetPort: 8081
    name: backend-oasis-svc
  selector:
    app: backend-oasis
  type: LoadBalancer