apiVersion: apps/v1
kind: Deployment 
metadata:
  name: backend-oasis
  namespace: gitlab-managed-apps
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend-oasis
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend-oasis
    spec:
      containers:
      - name: backend-oasis
        image: greenw00d/backend-oasis:TAG
        imagePullPolicy: Always
        env:
          - name: REDIS_HOST
            value: redis-master.default.svc.cluster.local
          - name: ESHOST
            value: elastic-cluster-es-http.default.svc.cluster.local
          - name: MONGO
            value: mongodb://se3-shard-mongos-0.se3-shard-svc.mongodb.svc.cluster.local,se3-shard-mongos-1.se3-shard-svc.mongodb.svc.cluster.local
          - name: SERVER_SERVLET_CONTEXT_PATH
            value: /prod
        readinessProbe:
            periodSeconds: 5
            httpGet:
              path: /prod/actuator/health
              port: 8081
            initialDelaySeconds: 360
        livenessProbe:
            periodSeconds: 2
            httpGet:
              path: /prod/actuator/health
              port: 8081
            initialDelaySeconds: 360
        resources:
          requests:
            memory: "300M"
            cpu: "0.25"
          limits:
            memory: "600M"
            cpu: "1"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: backend-oasis-svc
  namespace: gitlab-managed-apps
spec:
  ports:
  - port: 8081
    targetPort: 8081
    name: backend-oasis-svc
  selector:
    app: backend-oasis
  type: NodePort