version: '3'

services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    image: registry.cn-hangzhou.aliyuncs.com/rubiks-oasis/backend
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    links:
      - mongodb


#  mongodb:
#    restart: always
#    build:
#      dockerfile: Dockerfile
#      context: ./mongo
#    image: registry.cn-hangzhou.aliyuncs.com/rubiks-oasis/mongodb
#    ports:
#      - "27017:27017"
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:27017"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#    volumes:
#      - data-volume:/data/db
#
#volumes:
#  data-volume:

#  es:
#    image: elasticsearch:7.6.0
#    environment:
#      - discovery.type=single-node
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - network.host=0.0.0.0
#      - network.bind_host=0.0.0.0
#      - http.cors.enabled=true
#      - http.cors.allow-origin="*"
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:9200"]
#      interval: 30s
#      timeout: 10s
#      retries: 5

#  init_es:
#    build:
#      dockerfile: Dockerfile
#      context: ./init_es
#    image: registry.cn-hangzhou.aliyuncs.com/rubiks-oasis/init_es
#    restart: on-failure
#    depends_on:
#      - es
#    links:
#      - es