version: '3'

services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    image: registry.cn-hangzhou.aliyuncs.com/rubiks-oasis/backend
    environment:
      - ESHOST=es
    ports:
      - "8081:8081"

  es:
    image: elasticsearch:7.6.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  init_es:
    build:
      dockerfile: Dockerfile
      context: ./init_es
    image: registry.cn-hangzhou.aliyuncs.com/rubiks-oasis/init_es
    restart: on-failure
    depends_on:
      - es
    links:
      - es